### ISSUE TITLE
Smiple Question

### ISSUE THREAD

**Issue by rickyham** [thisandagain/sentiment#107]
This is a very sweet project!

I would like to know how can I convert the comparative value to a whole number (percentage 100), where 100 is the most positive, 50 is neutral and 0 is most negative?

This can also be out of 10.

**Comment by thisandagain** [comment]
The comparative score is simply: `sum of each token / number of tokens`. So for example let's take the following:
```
I love cats, but I am allergic to them.
```
That string results in the following:
```js
{
    score: 1,
    comparative: 0.1111111111111111,
    tokens: [
        'i',
        'love',
        'cats',
        'but',
        'i',
        'am',
        'allergic',
        'to',
        'them'
    ],
    words: [
        'allergic',
        'love'
    ],
    positive: [
        'love'
    ],
    negative: [
        'allergic'
    ]
}
```

Each token has a range between `5` (positive) and `-5` (negative). In this case, `love` has a value of `3`, `allergic` has a value of `-2`, and the remaining tokens are neutral with a value of `0`. Because the string has `9` tokens the resulting comparative score looks like:
```
(3 + -2) / 9 = 0.111111111
```

This approach leaves you with a mid-point of `0` and the upper and lower bounds are constrained to positive and negative `5` respectively (the same as each token! 😄 ). For example, let's imagine an incredibly "positive" string with 200 tokens and where each token has an AFINN score of `5`. Our resulting comparative score would look like this:
```
(max positive score * number of tokens) / number of tokens
(5 * 200) / 200 = 5
```

So – to answer your question – you can scale and offset the comparative score (`x`) however you like using simple arithmetic. For example:
```
Scale from 0 to 100
(x + 5) * 10
```

**Comment by rickyham** [comment]
Thank you very much! That was both fast and precisely detailed 👍.

And just so that I am clear. Taking the example you gave "I love cats, but I am allergic to them." would be:

Scale from 0 to 100
(0.1111111111111111+9)*10

And the value I am after would be: 91.11%

**Comment by thisandagain** [comment]
> `(0.1111111111111111+5)*10`

Yes. That's correct. To compute this you could do something like:
```js
function scale (score) {
    return (score + 5) * 100;
}

var result = scale(sentiment('I like cats').comparative);
```

but I would recommend diving into JS to get a better sense of the possibilities:
http://jsforcats.com/
https://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742

**Comment by rickyham** [comment]
Ahh yes, Mr Crockford (read that one already :)). Your awesome thanks! I will be able to build out the functionality, I'm not to shabby at Javascript.

And that function will work for all possibilities, including negatives, and neutral values?

**Comment by thisandagain** [comment]
> And that function will work for all possibilities, including negatives, and neutral values?

Yup. You can give it a try yourself to see how it works in all scenarios.

**Comment by rickyham** [comment]
Cool – thanks again!
