### ISSUE TITLE
Support for double negatives

### ISSUE THREAD

**Issue by PaulBGD** [thisandagain/sentiment#109]
Doing something like `Seth is not not amazing` gives a negative score.

**Comment by thisandagain** [comment]
Yup. This is a pretty well known limitation of this approach (AFINN).

**Comment by PaulBGD** [comment]
Yeah I figured, is there anything realistically that can be done about these things?

**Comment by markhighton** [comment]
compatible with Angular 2?

**Comment by PaulBGD** [comment]
@markhighton I think you might be on the wrong issue..

**Comment by thisandagain** [comment]
> Yeah I figured, is there anything realistically that can be done about these things?

@PaulBGD Sorry for the slow reply. Good question. The short answer is "yes" but not with the approach we are taking here. In order to handle double negatives (or "negation") well you really need to understand part-of-speech (PoS) which is not something the approach we take here does. We could of course expand our tokenizer to handle things like "not not" but most double negatives take a more subtle path:
```
I don't think I'll ever not be happy with my cats.
```

To handle these types of things you would likely want to use another approach which incorporates things like PoS, tokenizing, TFiDF, and sentiment.
