### ISSUE TITLE
Multiword Sentiments

### ISSUE THREAD

**Issue by manikumar-v** [thisandagain/sentiment#17]
Currently sentiment analyzer is not able to findout sentiments properly for multi-word like 
> "does not work": -3,

Below code is checking only one word at a time not multiple
```javascript
var len = tokens.length;
    while (len--) { 
        var obj = tokens[len];
        var item = afinn[obj];
        if (!afinn.hasOwnProperty(obj)) continue;

        words.push(obj);
        if (item > 0) positive.push(obj);
        if (item < 0) negative.push(obj);

        score += item;
    }
```

Fixed the same in my code.

**Comment by jeffthompson1971** [comment]
is this fix in base yet?  Also, any chance we can modify the afinn file itself that the moduel uses so that don't have to do it programmatcially all the time.   i'm using this for 'feedback' from agents on home showing (real estate) - gthere are no words for like 'smell', or 'odor' etc.   I'd like to feed in a bunch of real-estate word/ and phrases like 'they did not like' etc.   Can we do this ?

**Comment by manikumar-v** [comment]
Muliword - It is easily doable. I have the fix and it is working. If you
need I can check-in.

**Comment by thisandagain** [comment]
Tracking n-grams and negation in #23
