### ISSUE TITLE
Inverse words if not

### ISSUE THREAD

**Issue by auryn31** [thisandagain/sentiment#175]
Hy

is there a way to add inverses?
For example (`cats are not stupid`)? So that stupid is positiv in this situation?

Thanks for help

**Comment by elyas-bhy** [comment]
This library already handles this case. Have you tested it?
Refer to the files [/languages/en/scoring-strategy.js](https://github.com/thisandagain/sentiment/blob/develop/languages/en/scoring-strategy.js) and [/languages/en/negators.json](https://github.com/thisandagain/sentiment/blob/develop/languages/en/negators.json) if you're curious on how that works.

I'm closing this issue since this is already supported. Feel free to reopen it if necessary.

**Comment by auryn31** [comment]
I want to add a new language and asked myself, how can i add the negators...

**Comment by elyas-bhy** [comment]
Refer to [this README section](https://github.com/thisandagain/sentiment#adding-new-languages) to learn more about adding new languages.

**Comment by auryn31** [comment]
Thanks, but there is no part for negators.

Did i only have to add it to the language part with

```js
const language = {
    labels: {...},
    negators: {...} 
};
```

Thanks for the help

**Comment by elyas-bhy** [comment]
The negators are part of the scoring strategy, are not declared at the top-level. This is because some other languages have more complex negation constructs. Please refer to this repo's `languages/en` folder to see how to structure your files.

**Comment by auryn31** [comment]
Ok, thanks a lot.
