### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by thisandagain** [thisandagain/sentiment#24]
The AFINN wordlist is missing a fairly critical piece of contemporary discourse: the emoji. I'd like to add emoji support to sentiment. Major questions:
- Do any approaches to evaluating the sentiment of emoji exist?
- How do we tokenize emoji?
- Should this be an "opt-in" feature?
- How do we determine the accuracy of such an implementation?

**Comment by craigwinstanley** [comment]
Hi

Are the emojis part of the default wordlist or would these need to be added in?
I tried to manually append via code as i don't want to edit the wordlist directly using the following but it doesn't seem to take into account the smiley face ":)"

var analysis = sentiment(post.message, {
                            ':)': 5,
                            ':(': -3,
                            'xxx': 3,
                        });

The 'xxx' works correctly though so at first i thought it maybe because the word starts with punctuation and may be getting ignored?

Thanks any help would be greatly appreciated

Thanks

**Comment by thisandagain** [comment]
Good reference paper on the subject:
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144296

**Comment by dcworldwide** [comment]
Really good read, excited about the possibilities here.

**Comment by thisandagain** [comment]
Resolved in #74. Pending release.

**Comment by thisandagain** [comment]
Released!
